version: '3'
services:
  yii2:
    #image: yiisoftware/yii2-php:7.2-apache
    build: .
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8888:80'
      - '2222:22'
    network_mode: "host"
